import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Naukri Vacancy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"suppressHydrationWarning >
      <body suppressHydrationWarning>
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}