import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/AdminNavbar";

export const metadata = {
  title: "Naukri Vacancy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="dark:bg-bg-dark bg-bg-light dark:text-text-dark text-text-light"
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
