import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Naukri Vacancy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body suppressHydrationWarning >
          <Navbar />
          {children}
          <Footer />
        </body>
    </html>
  );
}